### ISSUE TITLE
"namespace verification failed"

### ISSUE THREAD

**Issue by mewmew** [letoram/senseye#14]
After building [arcan](https://github.com/letoram/arcan), and building [senseye](https://github.com/letoram/senseye) using an "in-source build" of arcan (i.e. `-DARCAN_SOURCE_DIR=/path/to/arcan/src`), I get the following errors when trying to run `senseye` using `arcan`.

Running `senseye` using `arcan` with debug output disabled.

```
u@x1 ~/D/s/build> /home/u/Desktop/arcan/build/arcan -p . -w 800 -h 800 /home/u/Desktop/senseye/senseye
namespace verification failed, status:
```

Running `senseye` using `arcan` with debug output enabled.

```
u@x1 ~/D/s/build> /home/u/Desktop/arcan/build/arcan -d -p . -w 800 -h 800 /home/u/Desktop/senseye/senseye
Couldn't load application (.)
	tried to load relative to current directory
```

Any thoughts on what step in the installation or configuration I may have missed?

FYI, `/home/u/Desktop/senseye` represents a clone of the [senseye](https://github.com/letoram/senseye) repository, and `/home/u/Desktop/arcan` a clone of the [arcan](https://github.com/letoram/arcan) repository.

**Comment by letoram** [comment]
-g for enabling debug output, in the way you invoked it there you would set "-p" as the name of the sqlite3 database to use. With '.' being the applname. So check the output for home/u/Desktop/arcan/build/arcan -g -g -p . -w 800 -h 800 /home/u/Desktop/senseye/senseye and it should tell you what files/folders it can't find.

**Comment by mewmew** [comment]
@letoram Thanks for the quick reply!

With enhanced verbosity, I get:

```
u@x1 ~/D/s/build> /home/u/Desktop/arcan/build/arcan -g -g -p . -w 800 -h 800 /home/u/Desktop/senseye/senseye
namespace verification failed, status:
fatal: main loop failed, arguments: 
/home/u/Desktop/arcan/build/arcan -g -g -p . -w 800 -h 800 /home/u/Desktop/senseye/senseye 

--- Verifying Namespaces: ---
application -- OK (/home/u/Desktop/senseye/senseye)
application-shared -- OK (.)
application-temporary -- OK (/home/u/Desktop/senseye/senseye)
application-state -- OK (./savestates)
system-applbase -- OK (/home/u/Desktop/senseye)
system-applstore -- OK (/home/u/Desktop/senseye)
system-statebase -- OK (./savestates)
system-font -- OK (/home/u/Desktop/senseye/senseye/fonts)
system-binaries -- broken
system-libraries(hijack) -- OK ((null))
system-debugoutput -- OK (./logs)
--- Namespace Verification Completed ---
```

`system-binaries -- broken` and perhaps `system-libraries(hijack)` with a `null` seem to be the issue. I'll try to dig deeper. Looking at `src/platform/posix/namespace.c` to try to see where it goes wrong.

**Comment by mewmew** [comment]
With the following patch to `arcan`

```diff
u@x1 ~/D/arcan> git diff
diff --git a/src/platform/posix/namespace.c b/src/platform/posix/namespace.c
index d0595ab..f3d12e3 100644
--- a/src/platform/posix/namespace.c
+++ b/src/platform/posix/namespace.c
@@ -260,9 +260,13 @@ void arcan_override_namespace(const char* path, enum arcan_namespaces space)
        if (path == NULL)
                return;
 
+       printf("path: %s\n", path);
+
        assert( space > 0 && (space & (space - 1) ) == 0 );
        int space_ind =i_log2(space);
 
+       printf("space_ind: %d\n", space_ind);
+
        if (namespaces.paths[space_ind] != NULL){
                if (namespaces.flags[space_ind])
                        return;
```

I get this output,

```
u@x1 ~/D/s/build> /home/u/Desktop/arcan/build/arcan -g -g -p . -w 800 -h 800 /home/u/Desktop/senseye/senseye
path: .
space_ind: 1
path: ./logs
space_ind: 10
path: ./savestates
space_ind: 3
path: ./fonts
space_ind: 7
path: ./savestates
space_ind: 6
path: /home/u/Desktop/senseye/senseye
space_ind: 0
path: /home/u/Desktop/senseye/senseye
space_ind: 2
path: /home/u/Desktop/senseye
space_ind: 4
path: /home/u/Desktop/senseye
space_ind: 5
path: ./savestates
space_ind: 3
path: /home/u/Desktop/senseye/senseye/fonts
space_ind: 7
namespace verification failed, status:
...
```

Any idea on what may be preventing *space index* 8 (i.e. "system-binaries") from being added?

**Comment by letoram** [comment]
ah it doesn't find the chainloader (arcan_frameserver), it's not used at all for senseye - but it's the middle- man that's responsible for checking/setting up environment for frameservers (afsrv_[decode, encode, terminal, game]). You can cheat by pointing -B /to/any/arcan_frameserver nonsensfile, it won't be executed in this case :)

**Comment by mewmew** [comment]
Wonderful! The work-around allowed `senseye` to be launched. Now I get stuck at the next step, adding a file for analysis using `sense_file`.

```
u@x1 ~/D/foo> /home/u/Desktop/senseye/build/sense_file d.exe
Senseye, attempting to connect to arcan using 'senseye' key
```

`sense_file` never seems to be able to establish a connection to arcan, but instead gets stuck at this stage.

![sense_file stuck at attempting to connect to arcan](https://i.imgur.com/vzYiUVv.png)

Any thoughts on why the connection fails to be established between `sense_file` and `arcan`?

**Comment by letoram** [comment]
Is this on 'BSD or Linux?

internally, the environment ARCAN_CONNPATH is used to find the unix domain socket to do connection negotiation (like X has DISPLAY=:0), if that env. isn't set, all the xlt_ and sense_ falls back to 'senseye' as the connection path.

The default on linux builds is that this socket is allocated in the hidden \0socketname namespace. If you strace on sense_file, does it stall on connecting to that one, or elsewhere? checking that arcan actually has the listening end active would also be helpful (should show up as open files covering a socket, named shared memory and named semaphores).

**Comment by mewmew** [comment]
Running on Arch Linux.

`strace` output shows that `sense_file` is trying to connect using the Unix socket to `/home/u/.arcan/.senseye` which does not exist. Is `arcan` supposed to create it?

```
u@x1 ~/D/foo> strace /home/u/Desktop/senseye/build/sense_file d.exe
execve("/home/u/Desktop/senseye/build/sense_file", ["/home/u/Desktop/senseye/build/se"..., "d.exe"], [/* 35 vars */]) = 0
brk(NULL)                               = 0xe3b000
...
open("d.exe", O_RDONLY)                 = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=757760, ...}) = 0
mmap(NULL, 757760, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f59e0988000
write(2, "Senseye, attempting to connect t"..., 59Senseye, attempting to connect to arcan using 'senseye' key) = 59
brk(NULL)                               = 0xe3b000
brk(0xe5c000)                           = 0xe5c000
socket(PF_LOCAL, SOCK_STREAM, 0)        = 4
connect(4, {sa_family=AF_LOCAL, sun_path="/home/u/.arcan/.senseye"}, 110) = -1 ENOENT (No such file or directory)
close(4)                                = 0
nanosleep({1, 0}, 0x7ffff8559120)       = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 4
connect(4, {sa_family=AF_LOCAL, sun_path="/home/u/.arcan/.senseye"}, 110) = -1 ENOENT (No such file or directory)
close(4)                                = 0
nanosleep({2, 0}, 0x7ffff8559120)       = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 4
connect(4, {sa_family=AF_LOCAL, sun_path="/home/u/.arcan/.senseye"}, 110) = -1 ENOENT (No such file or directory)
close(4)                                = 0
nanosleep({4, 0}, 0x7ffff8559120)       = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 4
connect(4, {sa_family=AF_LOCAL, sun_path="/home/u/.arcan/.senseye"}, 110) = -1 ENOENT (No such file or directory)
close(4)                                = 0
nanosleep({8, 0}, 0x7ffff8559120)       = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 4
connect(4, {sa_family=AF_LOCAL, sun_path="/home/u/.arcan/.senseye"}, 110) = -1 ENOENT (No such file or directory)
close(4)                                = 0
nanosleep({16, 0}, 0x7ffff8559120)      = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 4
connect(4, {sa_family=AF_LOCAL, sun_path="/home/u/.arcan/.senseye"}, 110) = -1 ENOENT (No such file or directory)
close(4)                                = 0
nanosleep({16, 0}, 0x7ffff8559120)      = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 4
connect(4, {sa_family=AF_LOCAL, sun_path="/home/u/.arcan/.senseye"}, 110) = -1 ENOENT (No such file or directory)
```

```
u@x1 ~> ls -la ~/.arcan
total 100
drwx------  2 u users  4096 May 28 13:38 ./
drwx------ 59 u users  4096 May 28 13:07 ../
-rw-r--r--  1 u users 90112 May 28 13:38 arcan.sqlite

```

**Comment by mewmew** [comment]
From `arcan` strace:

```
u@x1 ~/D/foo> strace /home/u/Desktop/arcan/build/arcan -B arcan_frameserver -g -g -p . -w 800 -h 800 /home/u/Desktop/senseye/senseye
...
bind(15, {sa_family=AF_LOCAL, sun_path=@"arcan_senseye"}, 110) = 0
fchmod(15, 0770)                        = 0
listen(15, 5)                           = 0
ftruncate(14, 2014088)                  = 0
...
```

The `arcan` strace contains no mention of the Unix socket `~/.arcan/.senseye` as far as I can tell, and only one call to `listen`.

**Comment by letoram** [comment]
Nice catch! This seems like a build-system bug in arcan, in that it selected one method for where to store/find the domain socket in libarcan-shmif and another in the main engine, I'm looking into it :)

**Comment by letoram** [comment]
Think I found it, it's in the senseye build-system actually, it picks different connection settings when it does the in-source build path -- it needs a __LINUX define, otherwise it will fallback to the ~/.arcan/. prefix

**Comment by letoram** [comment]
I pushed a fix to the build-system, did that solve it?

**Comment by mewmew** [comment]
> I pushed a fix to the build-system, did that solve it?

It did indeed! Thanks for fixing it so quickly. I've been happily playing around with senseye, love it so far!

I did manage to trigger an address boundary segmentation fault however. Luckily, it is reproducible on my system.

Follow these steps:

1. Start arcan
2. Use sense_file to explore a file
3. Change Views to Point Cloud
4. Set Sample Buffer Size to 64
5. SIGSEGV (Address boundary error)
6. ...
7. Profit?

In case it turns out not to be reproducible on your box, I've uploaded a video detailing the steps, and I'll attach the stack trace below.

https://www.dropbox.com/s/mqmq6unv863ugrc/arcan_out_of_bounds.ogv?dl=1

```
u@x1 ~/D/foo> /home/u/Desktop/arcan/build/arcan -B arcan_frameserver -g -g -p . -w 800 -h 800 /home/u/Desktop/senseye/senseye
...
Debug, resource lookup for images/background.png, yielded: /home/u/Desktop/senseye/senseye/images/background.png
(arcan_video_deleteobject(reference-pass) -- remove rendertarget (compsurf_1_wnd_7_canvas)
fish: “/home/u/Desktop/arcan/build/arc…” terminated by signal SIGSEGV (Address boundary error)
```

```
u@x1 ~/D/foo> coredumpctl gdb arcan
           PID: 15471 (arcan)
           UID: 1000 (u)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Sat 2016-05-28 15:49:05 CEST (1min 44s ago)
  Command Line: /home/u/Desktop/arcan/build/arcan -B arcan_frameserver -g -g -p . -w 800 -h 800 /home/u/Desktop/senseye/senseye
    Executable: /home/u/Desktop/arcan/build/arcan
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (u)
       Boot ID: 322e19b37c534b1e8e0e93bfe99b5f49
    Machine ID: 61a88ee686924c449891326de549222d
      Hostname: x1
      Coredump: /var/lib/systemd/coredump/core.arcan.1000.322e19b37c534b1e8e0e93bfe99b5f49.15471.1464443345000000000000.lz4
       Message: Process 15471 (arcan) of user 1000 dumped core.
                
                Stack trace of thread 15471:
                #0  0x00007ff5c4f62610 pthread_join (libpthread.so.0)
                #1  0x00000000004457bb arcan_ffunc_3dobj (arcan)
                #2  0x0000000000432c3a arcan_video_deleteobject (arcan)
                #3  0x000000000043291a arcan_video_deleteobject (arcan)
                #4  0x0000000000420808 deleteimage (arcan)
                #5  0x00007ff5c461c3c6 n/a (libluajit-5.1.so.2)
                #6  0x00007ff5c4661ba0 lua_pcall (libluajit-5.1.so.2)
                #7  0x0000000000416101 arcan_lua_pushevent (arcan)
                #8  0x0000000000411aae arcan_event_feed (arcan)
                #9  0x000000000042e0ed main (arcan)
                #10 0x00007ff5c37c4741 __libc_start_main (libc.so.6)
                #11 0x0000000000411269 _start (arcan)
                
                Stack trace of thread 15476:
                #0  0x00007ff5c4f67087 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007ff5bacb6798 pa_threaded_mainloop_wait (/usr/lib/libpulse.so.0.19.0)
                #2  0x00007ff5c3ba3429 n/a (libopenal.so.1)
                #3  0x00007ff5c3ba86c7 n/a (libopenal.so.1)
                #4  0x00007ff5c4f61474 start_thread (libpthread.so.0)
                #5  0x00007ff5c388b69d __clone (libc.so.6)
                
                Stack trace of thread 15475:
                #0  0x00007ff5c388268d poll (libc.so.6)
                #1  0x00007ff5bacb61b1 n/a (/usr/lib/libpulse.so.0.19.0)
                #2  0x00007ff5baca7761 pa_mainloop_poll (/usr/lib/libpulse.so.0.19.0)
                #3  0x00007ff5baca7dfe pa_mainloop_iterate (/usr/lib/libpulse.so.0.19.0)
                #4  0x00007ff5baca7eb0 pa_mainloop_run (/usr/lib/libpulse.so.0.19.0)
                #5  0x00007ff5bacb60f9 n/a (/usr/lib/libpulse.so.0.19.0)
                #6  0x00007ff5baa55b08 n/a (/usr/lib/pulseaudio/libpulsecommon-8.0.so)
                #7  0x00007ff5c4f61474 start_thread (libpthread.so.0)
                #8  0x00007ff5c388b69d __clone (libc.so.6)
```

I know this should belong in a dedicated issue, as the original issue of #14 has been resolved. Let me know, if you wish for me to open a dedicated issue for the out of bounds segmentation fault. Or you can simply copy this text and create the issue yourself, if you'd feel like it.

Cheers /u

**Comment by letoram** [comment]
don't have a decent issue tracker up for arcan yet (not particularly fond of the github one), but I think that trace is enough, smells like i treat the generated meshes like 3d model loading on deallocation. I need to think a little bit about the patch (that code is murky as hell and I suspect there's a race hidden there too). For the senseye case, you can just comment out the pthread_join call.

**Comment by mewmew** [comment]
> I'll close this issue for now and go and grab a beer. Poke me on IRC if you run into anything urgent ;D

Enjoy :)

P.S. You just answered most of my questions regarding #16.
